version: 2.1

jobs:
  validate:
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.0
      - run: "docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}"
      - run: ./build.sh

  push_docker_image:
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.0
      - run: "docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}"
      - run: ./build.sh
      - run: ./push-to-dockerhub.sh

workflows:
  main:
    jobs:
      - validate:
          filters:
            branches:
              ignore:
                - develop
                - master
      - push_docker_image:
          context:
            - docker-user
          filters:
            branches:
              ignore: /.*/
            tags: 
              only: /^[0-9]+\.[0-9]+\.[0-9]+$/
