version: 2.1

# NOTE: According to https://circleci.com/docs/2.0/building-docker-images , the CircleCI base images come with the Docker CLI preinstalled so we don't need to install it
jobs:
  validate:
    docker:
      - image: cimg/base:2020.01
        auth:
          username: ${DOCKER_USERNAME}
          password: ${DOCKER_PASSWORD}
    steps:
      - checkout
      - run: ./build.sh

  push_docker_image:
    docker:
      - image: cimg/base:2020.01
        auth:
          username: ${DOCKER_USERNAME}
          password: ${DOCKER_PASSWORD}
    steps:
      - checkout
      - run: ./build.sh
      - run: ./push-to-dockerhub.sh

workflows:
  main:
    jobs:
      - validate:
          filters:
            branches:
              ignore:
                - develop
                - master
      - push_docker_image:
          context:
            - docker-user
          filters:
            branches:
              ignore: /.*/
            tags: 
              only: /^[0-9]+\.[0-9]+\.[0-9]+$/
