version: 2.1

jobs:
  validate:
    docker:
      - image: cimg/base:2020.01
        auth:
          username: ${DOCKER_USERNAME}
          password: ${DOCKER_PASSWORD}
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.0
      - run: ./build.sh

  push_docker_image:
    docker:
      - image: cimg/base:2020.01
        auth:
          username: ${DOCKER_USERNAME}
          password: ${DOCKER_PASSWORD}
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.0
      - run: ./build.sh
      - run: ./push-to-dockerhub.sh

workflows:
  main:
    jobs:
      - validate:
          filters:
            branches:
              ignore:
                - develop
                - master
      - push_docker_image:
          context:
            - docker-user
          filters:
            branches:
              ignore: /.*/
            tags: 
              only: /^[0-9]+\.[0-9]+\.[0-9]+$/
