version: 2.1

orbs:
  kurtosis-docs-checker: kurtosis-tech/docs-checker@0.2.3

parameters:
  # To upgrade the Docker Engine version, see which versions are supported at: https://circleci.com/docs/2.0/building-docker-images/#docker-version
  docker-engine-version:
    type: string
    default: 20.10.18
  # To upgrade the CircleCI base image, see https://hub.docker.com/r/cimg/base/tags?page=1&ordering=last_updated
  circleci-base-image:
    type: string
    default: cimg/base:2022.06

# NOTE: According to https://circleci.com/docs/2.0/building-docker-images , the CircleCI base images come with the Docker CLI preinstalled so we don't need to install it
# We do still need to run `setup_remote_dockder` to get a Docker Engine, however
jobs:
  validate:
    docker:
      - image: "<< pipeline.parameters.circleci-base-image >>"
        auth:
          username: ${DOCKER_USERNAME}
          password: ${DOCKER_PASSWORD}
    steps:
      # Install kudet
      - run: |
          echo "deb [trusted=yes] https://apt.fury.io/kurtosis-tech/ /" | sudo tee /etc/apt/sources.list.d/kurtosis.list
          sudo apt update
          sudo apt install kudet
      - checkout
      - setup_remote_docker:
          version: "<< pipeline.parameters.docker-engine-version>>"
      - run: scripts/build.sh build

  push_docker_image:
    docker:
      - image: "<< pipeline.parameters.circleci-base-image >>"
        auth:
          username: ${DOCKER_USERNAME}
          password: ${DOCKER_PASSWORD}
    steps:
      # Install kudet
      - run: |
          echo "deb [trusted=yes] https://apt.fury.io/kurtosis-tech/ /" | sudo tee /etc/apt/sources.list.d/kurtosis.list
          sudo apt update
          sudo apt install kudet
      - checkout
      - setup_remote_docker:
          version: "<< pipeline.parameters.docker-engine-version>>"
      - run: docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
      - run: scripts/build.sh publish

workflows:
  main:
    jobs:
      - kurtosis-docs-checker/check-docs:
          should-check-changelog: false
          markdown-link-check-config-json: |
            {
                "ignorePatterns": [
                    {
                        "pattern": "https://github.com/kurtosis-tech/iproute2-container"
                    }
                ]
            }          
          filters:
            branches:
              ignore:
                - main
      - validate:
          filters:
            branches:
              ignore:
                - develop
                - main
      - push_docker_image:
          context:
            - docker-user
          filters:
            branches:
              ignore: /.*/
            tags: 
              only: /^[0-9]+\.[0-9]+\.[0-9]+$/
